### ISSUE TITLE
Single line

### ISSUE THREAD

**Issue by simondate** [shillingp/atom-lorem#10]
When pasting into JSON it doesn't work unless everything is a single line. It would be great if you could add a feature to make everything appear on a single line. Currently I have to use this tool https://wordhtml.com/

**Comment by shillingp** [comment]
This is a very good idea, when i get some time i will look into it

**Comment by shillingp** [comment]
I have created a solution to this problem however I have not done extensive testing or written any tests and i am particularly busy at the moment so I will try to push a new version of the package in a couple of weeks.

**Comment by simondate** [comment]
Ah, excellent thanks very much! Is there a branch I can checkout to test myself?

**Comment by shillingp** [comment]
I will try to get at least the code pushed to github in the next few days. Many thanks

**Comment by simondate** [comment]
Just tried now and it works perfectly! 😍 

Thank you! I'm sure this will save me countless hours in the future :)
