### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by willthemoor** [shillingp/atom-lorem#11]
How in the world have I lived this long without this package?? SO GREAT!

Would like to add an option to capitalize the first character of the inserted text either via appending `_C`(`_c`?) and/or via a fixed config setting ["Always capitalize the first word"]. I don't have much (ok, any...) experience hacking atom packages so when looking through the code I'm not sure where to begin. 

Can you point me in a direction? Happy to issue a PR if I manage to make anything useful.

**Comment by shillingp** [comment]
Hi @willthemoor  I have been thinking about this issue and wanted some clarification, are you looking for something that is only used when inserting words (i.e. `lorem_w5`). As it currently stands the text that comes from using sentence or paragraphs `lorem_s2` `lorem_p` will be correctly capitalized, and any other command that uses sentence or paragraphs (i.e. lists, html, links etc).

So yes the question, is it only for words

**Comment by willthemoor** [comment]
Hi @shillingp. That is correct. Sorry I should have been clearer. It comes up when inserting UI text like menu items, labels, etc where `_s` or `_p` or generally too long. Maybe there's a different way to go about this though?

**Comment by willthemoor** [comment]
Aha! I just found the `_short` modifier. `lorem_s_short` does exactly what I'm looking for. Going to close this out. Sorry for the noise!
