### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by ldwyze** [shillingp/atom-lorem#7]
Not sure if I am just missing something on how to use the package but I have tried issuing lorem commands such as lorem_s5 (press enter or tab) or lorem_p3 (enter or tab) and even just tried alt+1 and I get nothing at all.

Atom version 1.25.1 X64
MSI laptop
Windows 8.1 64Bit
12 Gigs Ram

**Comment by ldwyze** [comment]
Nevermind.  Uninstalled.  Garbage.

**Comment by ldwyze** [comment]
doesn't work and no support

**Comment by Akimyou** [comment]
@ldwyze 
- Atom: 1.26.0 x86
- OS:macOS 10.12.3 (16D32)

I can use it.

```js
lorem_p1 // Press the alt+l
```

**Comment by ldwyze** [comment]
@akimyou

You are using a different version of Atom on a completely different OS. So you being able to use it is irrelevant.

**Comment by shillingp** [comment]
@ldwyze I am sorry for not getting back to you quickly.
As @Akimyou noted the keys you need to use are `alt + l` not `alt + 1` note the difference is `l` for lorem

**Comment by ldwyze** [comment]
The package does not work.  Just nevermind.  The default Atom package can do lorem ipsum text just fine.  This package is not even needed really.
