### ISSUE TITLE
Commands and alt+l not working

### ISSUE THREAD

**Issue by davim00** [shillingp/atom-lorem#9]
When I type "lorem" then hit tab, the expected default paragraph is inserted. When I type any other command, such as "lorem_w10" (for 10 words) and hit tab I just tab over. No text is inserted. Also, when I use alt+l it opens my web browser to the atom-lorem readme on Github.

I am on Windows 10, Atom 1.31.1 x64. I have not changed the package settings from the default.

**Comment by shillingp** [comment]
Using the tab key will not do anything, the command is alt+l. The browser
should only open under certain circumstances. Please could you try and type
lorem_w2 then press alt+l.

**Comment by davim00** [comment]
I used alt+l after typing lorem_w2 and it opened the web browser to the readme on Github (https://github.com/shillingp/atom-lorem#how-to-use). I even tried changing the keybinding to alt+/ in case there was a conflict with another plugin and it still presented the same behavior.

**Comment by shillingp** [comment]
Thank you for letting me know I will have to look into this.

**Comment by shillingp** [comment]
The `showHelp: true` appearing in atom config file means that the package settings have been changed.
